### ISSUE TITLE
Embedded link

### ISSUE THREAD

**Issue by mbtools** [marianfoo/bluesky-bots#1]
Hi Marian

I love the bot! Nicely done. It also serves as a template for making more. Thanks!

The embedded links were better since they are formatted, have a preview, and don't show the url. 

I would keep them with just a minimal intro:

`📰 Blog by xyz (Member):`
Or
`🔖 Post by abc (SAP):`

**Comment by marianfoo** [comment]
short survey was pretty clear, not using embedded
